wordCount:     wordCount.o
	                g++ -std=c++17 wordCount.o -o wordCount

wordCount.o:   wordCount.cc
	                g++ -g -Wall -std=c++17 -c wordCount.cc

clean:
	                rm *.o wordCount
